name: Report vulnerability of a system app
description: Ask maintainers to add/update vulnerability of a system app
labels: [enhancement]

body:
  - type: checkboxes
    attributes:
       label: Please check before submitting an issue
       options:
          - label: I have investigated the app and created a report
            required: true

  - type: input
    attributes:
        label: Vulnerability report
        description: CVD/CVE, or a link otherwise
        placeholder: CVE-2019-16253
    validations:
        required: true

  - type: input
    attributes:
        label: Package name
        placeholder: com.samsung.SMT
    validations:
      required: true

  - type: input
    attributes:
        label: Package label
        placeholder: Samsung TTS
    validations:
      required: true

  - type: textarea
    attributes:
        label: Affected versions
        description: List affection versions with version code
        placeholder: |
          - Android < P: 3.0.00.100 (300200100) and earlier
          - Android ≥ P: 3.0.02.6 (300200006) and earlier
    validations:
      required: true

  - type: input
    attributes:
      label: Removal
      placeholder: Update, or remove if the feature is not used
    validations:
      required: true

  - type: textarea
    attributes:
        label: Additional context
        description: Add any other context about your proposal here.
